### ISSUE TITLE
can install waldur 

### ISSUE THREAD

**Issue by chelseasura** [waldur/waldur-helm#4]
when i install with   

`helm install waldur waldur`

and got result 

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1alpha2"`

and check cert-manager.io

![image](https://user-images.githubusercontent.com/25239898/158153616-9a18a567-cd21-4151-b88f-29caa1f080e8.png)

**Comment by sergei-zaiaev** [comment]
Hi!

Could you please provide a version of your k8s cluster and `apiVersion` of the ClusterIssuer?

**Comment by sergei-zaiaev** [comment]
Also, there is a related issue: [link](https://github.com/cert-manager/cert-manager/issues/2796)

**Comment by chelseasura** [comment]
> Hi!
> 
> Could you please provide a version of your k8s cluster and `apiVersion` of the ClusterIssuer?

![image](https://user-images.githubusercontent.com/25239898/158286141-278ea849-cdbf-4b0d-8d30-016356886b42.png)

**Comment by chelseasura** [comment]
> Hi!
> 
> Could you please provide a version of your k8s cluster and `apiVersion` of the ClusterIssuer?

![image](https://user-images.githubusercontent.com/25239898/158286558-e718a57e-bf82-467f-93a3-dce8ce22d42e.png)

**Comment by chelseasura** [comment]
replace ./letsencrypt-issuer.yaml in the template with version in my system ,it works

**Comment by sergei-zaiaev** [comment]
Fixed here: https://github.com/waldur/waldur-helm/commit/287498233d9a8e79b6b5fc1f3d593ea9b45ae465
