### ISSUE TITLE
error: unable to upgrade connection: container not found

### ISSUE THREAD

**Issue by chelseasura** [waldur/waldur-helm#5]
![image](https://user-images.githubusercontent.com/25239898/158343203-19b4ed6b-fd41-401b-8899-ed23f4134b5e.png)

![image](https://user-images.githubusercontent.com/25239898/158343368-a5897620-b64c-4b68-bf07-279eb1e804bf.png)

**Comment by chelseasura** [comment]
![image](https://user-images.githubusercontent.com/25239898/158344283-24d9032c-5b8a-4be1-9084-a096e579da7d.png)

it works some time and not work other time

**Comment by sergei-zaiaev** [comment]
Could you please provide logs of the container?

**Comment by chelseasura** [comment]
> Could you please provide logs of the container?

![image](https://user-images.githubusercontent.com/25239898/158508138-473342c5-dfec-4f5a-9ca9-12de8218d93d.png)

**Comment by chelseasura** [comment]
![image](https://user-images.githubusercontent.com/25239898/158508225-2ca30c7e-3830-410b-bfac-4bfced9f0b5f.png)

when i want create admin user

**Comment by sergei-zaiaev** [comment]
And what is the content of `values.yaml` file? Also, what namespace do you use?

**Comment by sergei-zaiaev** [comment]
Did you specify any memory limits? Error 137 may indicate running out of memory [link](https://komodor.com/learn/how-to-fix-oomkilled-exit-code-137/)

**Comment by chelseasura** [comment]
> And what is the content of `values.yaml` file? Also, what namespace do you use?

default namaspace ,and not specify memory limits ,i not reset the param in the github file

**Comment by livenson** [comment]
closing as no response was received
