### ISSUE TITLE
W0315 18:12:39.840072 3750162 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob

### ISSUE THREAD

**Issue by chelseasura** [waldur/waldur-helm#6]
![image](https://user-images.githubusercontent.com/25239898/158356175-b8b41695-df92-4662-aefa-6a9d16e04a2d.png)

**Comment by chelseasura** [comment]
![image](https://user-images.githubusercontent.com/25239898/158356750-17d106dc-097c-44b5-b505-d5e8eb075119.png)

**Comment by sergei-zaiaev** [comment]
Fixed here: https://github.com/waldur/waldur-helm/commit/e1f96f385aefafd7bd9d62b0c3b80601bad93ebb
