### ISSUE TITLE
Working on dev env

### ISSUE THREAD

**Issue by umberto10** [waldur/waldur-helm#7]
Is it possible to run autogenerated self-signed certs? because I wanted to run waldur on my dev env and I don't have legit certificate :v
I saw that, in the docker-compose deployment it is possible, but I couldn't find how to achieve it via helm deployment :/

**Comment by livenson** [comment]
Such a setup is covered in documentation: https://github.com/waldur/waldur-helm/blob/master/docs/tls-config.md#your-own-certificate
