### ISSUE TITLE
initDB should be not be helm hook

### ISSUE THREAD

**Issue by sspreitzer** [waldur/waldur-helm#8]
https://github.com/waldur/waldur-helm/blob/f94d0515bf04c2080074cbc6aef74eec22dd862c/waldur/templates/job-initdb.yaml#L9C1-L9C1

InitDB job should be created parallel to other services and loop in connect attempts until DB is up and ready.

Helm hook will add circular dependency, which for example in ArgoCD will never have the job created as deployments will never succeed.

Kubernetes good practise is initContainers or startupProbes.

**Comment by sspreitzer** [comment]
This helm chart is thereof currently unusable with ArgoCD.

**Comment by sergei-zaiaev** [comment]
Hi!

Thank you for the note!
We are working on a possible solution for this.

Please tell me if you use the `--wait` flag for helm install/upgrade commands. If not, what exactly causes the error in ArgoCD?

Thank you in advance!

**Comment by sergei-zaiaev** [comment]
Hi!

We have [added](https://github.com/waldur/waldur-helm/commit/6eba0deb178d67406b27a95470c15b367a075408) ArgoCD's hooks to the `initdb` and `bootstrap` jobs, so now:
* initdb is a PreSync hook
* bootstrap is a ProstSync hook

Could you please try `waldur-helm` with the updated jobs?

**Comment by livenson** [comment]
Please reopen if you still have an issue.
