### ISSUE TITLE
Issue with letsencrypt-prod-issuer in Helm installation

### ISSUE THREAD

**Issue by bugblasterX** [waldur/waldur-helm#9]
Hello,

when following Waldur's installation documentation, when running `helm install waldur waldur` I get the following error:
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "letsencrypt-prod-issuer" namespace: "" from "": no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
ensure CRDs are installed first`

**Comment by sergei-zaiaev** [comment]
Fixed in https://github.com/waldur/waldur-helm/commit/bf3122a737b069c6ffb01612cd2d5cc4fd38dadc
